services:
  - type: web
    name: sistema-citas-consultorio
    env: node
    rootDir: api
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_CLIENT
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        sync: false
      - key: DB_SSL_REJECT_UNAUTHORIZED
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: COOKIE_SAMESITE
        value: none
      - key: COOKIE_SECURE
        value: true