tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "secondary-fixed-dim": "#bfc8d0",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#181c20",
                "on-secondary": "#ffffff",
                "on-tertiary-container": "#ffffff",
                "surface-container-low": "#f1f4f9",
                "surface-bright": "#f7f9ff",
                "primary": "#0057cd",
                "surface-variant": "#e0e3e8",
                "on-primary": "#ffffff",
                "outline-variant": "#c2c6d8",
                "tertiary-fixed": "#e1e3e4",
                "surface-tint": "#0057ce",
                "error": "#ba1a1a",
                "on-primary-fixed": "#001946",
                "on-tertiary-fixed-variant": "#454748",
                "secondary": "#575f67",
                "on-background": "#181c20",
                "on-secondary-fixed-variant": "#3f484f",
                "on-tertiary": "#ffffff",
                "primary-container": "#0d6efd",
                "tertiary-fixed-dim": "#c5c7c8",
                "primary-fixed-dim": "#b1c5ff",
                "surface": "#f7f9ff",
                "outline": "#727787",
                "on-secondary-container": "#5b646b",
                "tertiary": "#5c5e60",
                "on-error": "#ffffff",
                "background": "#f7f9ff",
                "surface-container": "#ebeef3",
                "tertiary-container": "#757778",
                "inverse-on-surface": "#eef1f6",
                "surface-container-high": "#e5e8ee",
                "on-error-container": "#93000a",
                "primary-fixed": "#dae2ff",
                "on-primary-container": "#ffffff",
                "secondary-fixed": "#dbe4ed",
                "on-secondary-fixed": "#141d23",
                "error-container": "#ffdad6",
                "surface-container-highest": "#e0e3e8",
                "inverse-primary": "#b1c5ff",
                "on-tertiary-fixed": "#191c1d",
                "surface-dim": "#d7dadf",
                "on-primary-fixed-variant": "#00419e",
                "on-surface-variant": "#424655",
                "inverse-surface": "#2d3135",
                "secondary-container": "#d8e1ea"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-md": "1rem",
                "stack-sm": "0.5rem",
                "margin-mobile": "1rem",
                "gutter": "1.5rem",
                "stack-lg": "2rem",
                "margin-desktop": "2rem",
                "container-max-width": "1320px"
            },
            "fontFamily": {
                "headline-lg-mobile": ["Inter"],
                "body-sm": ["Inter"],
                "body-lg": ["Inter"],
                "headline-md": ["Inter"],
                "label-md": ["Inter"],
                "headline-sm": ["Inter"],
                "label-sm": ["Inter"],
                "body-md": ["Inter"],
                "headline-lg": ["Inter"]
            },
            "fontSize": {
                "headline-lg-mobile": ["2rem", { "lineHeight": "1.2", "fontWeight": "700" }],
                "body-sm": ["0.875rem", { "lineHeight": "1.5", "fontWeight": "400" }],
                "body-lg": ["1.125rem", { "lineHeight": "1.6", "fontWeight": "400" }],
                "headline-md": ["2rem", { "lineHeight": "1.3", "fontWeight": "600" }],
                "label-md": ["0.875rem", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }],
                "headline-sm": ["1.5rem", { "lineHeight": "1.4", "fontWeight": "600" }],
                "label-sm": ["0.75rem", { "lineHeight": "1", "letterSpacing": "0.03em", "fontWeight": "600" }],
                "body-md": ["1rem", { "lineHeight": "1.5", "fontWeight": "400" }],
                "headline-lg": ["2.5rem", { "lineHeight": "1.2", "fontWeight": "700" }]
            }
        }
    }
};
